python-social-auth/social-docs

docs/backends/github.rst
docs/backends/github_enterprise.rst
docs/backends/implementation.rst
docs/backends/shopify.rst
docs/intro.rst
site/index.html

In all of GitHub's branding, the "H" in GitHub is capitalized. We should respect GitHub's branding, and use a capital H when referring to it in the documentation.
Note that the codebase already uses `Github` in several class names, and this pull request doesn't change that. It might be a good idea to switch those over in the future, as well.

GitHub has a capital H

---

docs/backends/stripe.rst

Use the correct Setting name for auth backends.
Fixes python-social-auth/social-core#38

Fix Stripe Documentation

---

docs/backends/google.rst

Use `id_token` in the Google Plus Auth Examples

---

docs/configuration/settings.rst
docs/use_cases.rst

As per description in the subsequent paragraph, this setting seems to be missing the omnipresent `SOCIAL_AUTH`-prefix to its name.

config setting missing SOCIAL_AUTH_-prefix

---

docs/backends/facebook.rst

This updates the documentation to match the default version actually used in the code ([source link](https://github.com/python-social-auth/social-core/blob/1.4.0/social_core/backends/facebook.py#L17)).

Update used Facebook API version: 2.8 -> 2.9

---

docs/backends/saml.rst

There were two `SOCIAL_AUTH_SAML_TECHNICAL_CONTACT` entries. Also normalizes `SOCIAL_AUTH_SAML_TECHNICAL_CONTACT` and `SOCIAL_AUTH_SAML_SUPPORT_CONTACT` to match the rest of examples in the document.

Fixes documention for SOCIAL_AUTH_SAML_SUPPORT_CONTACT

---

docs/backends/apple.rst

It provides documentation for the new (pending to merge) `AppleID` backend.
Related to https://github.com/python-social-auth/social-core/pull/409 and https://github.com/python-social-auth/social-core/issues/370

Add apple backend

---

docs/backends/linkedin.rst

LinkedIn removed the support for Oauth1 & updated the scope names.
I have created a PR for social-core changes [here](https://github.com/python-social-auth/social-core/pull/322).
Update the documentation to reflect the same.

Updated LinkedIn documentation

---

docs/backends/aol.rst
docs/backends/belgium_eid.rst
docs/backends/fedora.rst
docs/backends/google.rst
docs/backends/implementation.rst
docs/backends/index.rst
docs/backends/launchpad.rst
docs/backends/livejournal.rst
docs/backends/openid.rst
docs/backends/steam.rst
docs/backends/suse.rst
docs/backends/yahoo.rst
docs/configuration/settings.rst
docs/index.rst
docs/installing.rst
docs/intro.rst
docs/storage.rst
docs/tests.rst

Correct references to the OpenID ecosystem to have a capitalized 'D' at the end if not a code (module or variable) reference to be consistent with the spec's official name.

correct name references to OpenID

---

docs/configuration/django.rst

Update the order of associate_by_email in the Django docs.

---

CHANGELOG.md
docs/backends/index.rst
docs/backends/patreon.rst

- Adds documentation about using Patreon OAuth2 backend
- Adds documentation to list of documented backends
- Updates changelog
Verification: Built and viewed docs locally.

Fixes #46 - Document Patreon OAuth2 backend

---

docs/backends/twitter.rst

Fixes https://github.com/python-social-auth/social-core/issues/249
Our Twitter OAuth started to fail recently as our Callback URL wasn't right. Fixed it by editing the app's settings in the Twitter dashboard. Then found this ticket so here is the update.

Update Twitter docs about the recent changes on the callback URL

---

docs/index.rst
docs/maintainers.rst

This PR introduces a `maintainers` section to the doc in order to list the team in charge of this task.

Add maintainers sections

---

docs/configuration/django.rst

This PR ports the documentation found at https://github.com/python-social-auth/social-app-django/blob/e39b481225104913fa355b6d681006e3a15c9a8f/CHANGELOG.md#L16-L46. A link to this doc will be added to that changelog instead.

Port Django JSON field integration doc

---

docs/backends/index.rst
docs/backends/osso.rst

Adds documentation for Osso per https://github.com/python-social-auth/social-core/pull/564
I'm having a lot of trouble figuring out how to lint/ autoformat these restructured text files. 
I see the Pep8 note in contributing doc, I guess that's been renamed to `pycodestyle`?
If someone could point me in the right direct for how to format from CLI or VSCode (im using venv) that would be super helpful. I'd be happy to update the contributing docs

Add (unformatted) osso docs

---

docs/developer_intro.rst

`backend_name` doesn't exist in this context, but `backend.name` is valid.

Fix: `backend_name` should be `backend.name` in example code.

---

docs/backends/shopify.rst

The existing documentation is missing a few steps to set up and use the Shopify backend. This PR fills in those gaps.

docs: update Shopify backend documentation

---

docs/configuration/django.rst

Help people not to shoot themselves in the foot by first highlighting the JSONFIELD
setting and only then pointing to migrate, if you first migrate it's much harder to fix 
this setting later.
Also fixed the JSONFIELD setting to the latest recommended since Django 3.1

Update Django database docs

---

.github/dependabot.yml
.readthedocs.yaml
docs/requirements.txt

This should avoid sudden build failures.
See https://github.com/readthedocs/readthedocs.org/issues/8616

deps: Pin readthedocs environment

---

docs/backends/azuread.rst

Updates to some incorrect naming and to match the updates in https://github.com/python-social-auth/social-core/pull/777.

Update documentation for Azure AD B2C

---

docs/backends/yahoo.rst

Fixed module 'social_core.backends.yahoo' has no attribute 'YahooOpenId'
**Problem**
Instead of :
```
AUTHENTICATION_BACKENDS = (
...
'social_core.backends.yahoo.YahooOpenId',
...
)
```
we should have 
```
AUTHENTICATION_BACKENDS = (
...
'social_core.backends.yahoo.YahooOAuth2',
...
)
```

fixed attribute 'YahooOpenId' not found

---

docs/backends/linkedin.rst

Add docs for Linkedin OpenID Connect

---

docs/backends/index.rst
docs/backends/lifescience.rst

Added docs for [Life science AAI](https://lifescience-ri.eu/ls-login.html) backend.

feat: Lifescience AAI backend documentation
