- docs/backends/github.rst
Added some information that confused me when I was using the module in a more explicit way :)
> Added github documentation

- docs/configuration/django.rst
Added some documention on pipelines that were useful to me. Tried to make it more explicit
> Added django pipelines documentation

- docs/use_cases.rst
> Before you create a pull request, please review **[the guidelines for contributing](https://github.com/python-social-auth/social-docs/blob/master/CONTRIBUTING.md)** to this repository.
I didn't create a CHANGELOG entry, because this is just a trivial fix of a typo (that wasn't distorting the meaning) and http://keepachangelog.com/en/0.3.0/ says:
> ### What’s the point of a change log?
> 
> To make it easier for users and contributors to see precisely what **notable** changes have been made between each release (or version) of the project.
(emphasis mine)
For the same reason, I didn't file an issue before filing this pull request. Because I've edited this online on GitHub without making a local clone of the repository, I couldn't run `pep8` or any tests, either. (Though, as far as I can …
> fix typo (misplaced space)

- docs/backends/udata.rst
Related to https://github.com/python-social-auth/social-core/pull/82
> Add docs for udata/datagouv related backend

- docs/backends/orcid.rst
Documentation of the implemented ORCID OAuth 2 backend (https://github.com/python-social-auth/social-core/pull/75).
> Added the documentation of ORCID backend

- docs/backends/vk.rst
Update documentation after changes in https://github.com/python-social-auth/social-core/pull/65
> Documentation update after changes

- docs/backends/bungie.rst
Add Docs for OAuth2.0 support for Bungie.net
> python-social-auth#96

- CHANGELOG.md
- docs/backends/eventbrite.rst
- docs/backends/index.rst
- docs/intro.rst
https://github.com/python-social-auth/social-docs/issues/31
> Added Eventbrite OAuth2 backend documentation

- docs/use_cases.rst
Resolves issue https://github.com/python-social-auth/social-docs/issues/33
> Reuse `token` variable

- docs/backends/apple.rst
> fix:apple doc typo mistake

- CHANGELOG.md
- docs/backends/simplelogin.rst
This PR is relative to the one that adds SimpleLogin to `social-core`: https://github.com/python-social-auth/social-core/pull/385
> Add SimpleLogin documentation

- docs/backends/github.rst
https://github.com/python-social-auth/social-core/pull/413
> Document new GitHubApp backend

- CHANGELOG.md
- docs/backends/discourse.rst
- docs/backends/index.rst
- docs/storage.rst
Related to PR: https://github.com/python-social-auth/social-core/pull/384
Addresses: https://github.com/python-social-auth/social-core/issues/383
> Add docs for Discourse backend

- docs/backends/index.rst
- docs/backends/okta.rst
Documentation for https://github.com/python-social-auth/social-core/pull/333
> Add information on Okta backend

- docs/backends/implementation.rst
I would have done more, but I ran out of time.
> Lots of grammar changes

- docs/backends/linkedin.rst
- docs/configuration/django.rst
- docs/configuration/flask.rst
- docs/configuration/porting_from_dsa.rst
- docs/configuration/settings.rst
- docs/tests.rst
Fixing spelling and grammar issues as I find them working through the documentation.
> grammar and spelling fixes

- docs/backends/flat.rst
- docs/backends/index.rst
- docs/intro.rst
Ref: python-social-auth/social-core#267
> Add Flat backend doc

- docs/pipeline.rst
These are just some small typos.
> pipeline.rst: Fix some small typos

- docs/backends/battlenet.rst
- docs/use_cases.rst
This avoids a few instances of unnecessary male defaulting in the text.
> Use gender-neutral pronouns (his → their)

- docs/backends/index.rst
- docs/developer_intro.rst
- docs/index.rst
- docs/installing.rst
Remove obsolete easy_install instructions, update PyPI link, improve
grammar and formatting, and add GitHub link to welcome open source
contributions.
Fixes #38.
Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
> Improve grammar and links in documentation.

- docs/backends/saml.rst
As I had the issue myself, maybe this paragraph spares others from digging through the python-saml documentation.
> saml rollover cert documentation

- docs/backends/index.rst
- docs/backends/keycloak.rst
- docs/intro.rst
Added Keycloak as a backend to the documentation
_Please could someone review the restructured text as I have not used it at all_
> Documentation: Add keycloak as backend 

- docs/backends/index.rst
- docs/backends/microsoftgraph.rst
> add microsoft-graph backend

- docs/backends/twitter.rst
Fixes https://github.com/python-social-auth/social-app-django/issues/360
> Clarify Twitter access levels

- docs/backends/implementation.rst
> docs: nits for implementation doc

- docs/backends/azuread.rst
Add docs for Azure AD B2C tenant options
Add Azure `AUTHORITY_HOST` setting docs
> Azure AUTHORITY_HOST setting

- CHANGELOG.md
- docs/backends/grafana.rst
- docs/backends/index.rst
https://github.com/python-social-auth/social-core/pull/688
> Add Grafana backend

- docs/backends/index.rst
- docs/backends/oidc.rst
- docs/backends/vault.rst
Follow up to https://github.com/python-social-auth/social-core/pull/669
CC @candlerb
> Add documentation for vault and oidc backends

- docs/backends/qiita.rst
ref: https://github.com/python-social-auth/social-core/pull/698
> Add description of SOCIAL_AUTH_QIITA_IDENTIFIED_BY_PERMANENT_ID

- CHANGELOG.md
- docs/backends/index.rst
- docs/backends/seznam.rst
Related social-core PR: https://github.com/python-social-auth/social-core/pull/736
> Add Seznam backend

- docs/backends/cas.rst
- docs/backends/index.rst
See PR for implementation: https://github.com/python-social-auth/social-core/pull/743
> CAS: Document the CAS-OIDC backend.

- CHANGELOG.md
- docs/backends/index.rst
- docs/backends/twitter_oauth2.rst
- Related to PR: python-social-auth/social-core#791
- Addresses: python-social-auth/social-core#792
> Add docs for Twitter API v2 backend

- docs/backends/discogs.rst
- docs/backends/index.rst
This is the documentation for adding the Discogs OAuth1 backend.
The PR to add the functionality is https://github.com/python-social-auth/social-core/pull/853
> Added documentation to use the Discogs backend

- docs/backends/azuread.rst
I was adding a single-tenant Azure AD authentication to my project. Everything was working except after the user logged in, it didn't seem as if s/he logged in to their account.
After googling the error to see if anyone encountered that error before, I came across [this issue](https://github.com/python-social-auth/social-app-django/issues/111).
[This comment](https://github.com/python-social-auth/social-app-django/issues/111#issuecomment-1085135842) fixed my error. It seems that the backend path for a single-tenant Microsoft Azure AD is not correct. This PR fixes that problem.
Credit: @pizzapanther
the PR. If you're unsure about any of them, don't hesitate to …
> docs: fix the backend path for single tenant azure ad authentication

- CHANGELOG.md
- docs/backends/bitbucket_datacenter_oauth2.rst
- docs/backends/implementation.rst
- docs/backends/index.rst
- docs/thanks.rst
Related issue on social-core: https://github.com/python-social-auth/social-core/issues/855
Related PR on social-core: https://github.com/python-social-auth/social-core/pull/856
your code._
> docs: new implementation OAuth2 with PKCE, new backend Bitbucket Data Center

- docs/configuration/settings.rst
Update documentation for requests-related settings to:
- Update outdated settings `SOCIAL_AUTH_URLOPEN_TIMEOUT` which seems like a deprecated one, dating back from before https://github.com/python-social-auth/social-core/commit/904978f86d14a656c04e8774c1d507b4d61a8bfc
- Mention corresponding setting for `requests`
- Add missing settings for customising verify SSL and proxies
your code._
the component looks before and after …
> Update docs for requests settings

- CHANGELOG.md
- docs/backends/etsy.rst
- docs/backends/index.rst
- docs/thanks.rst
- Related Issue: https://github.com/python-social-auth/social-core/issues/872
- Related PR: https://github.com/python-social-auth/social-core/pull/874
> docs: Added Etsy OAuth2 Documentation

- CHANGELOG.md
- docs/backends/index.rst
- docs/backends/openstreetmap.rst
- docs/backends/openstreetmap_oauth2.rst
Added docs for OpenStreetMap OAuth 2.0.
Also added deprecation notice  for OAuth 1.0a, according to official communication in https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490
your code._
https://github.com/python-social-auth/social-core/pull/877
> docs: Added OpenStreetMap OAuth2 Documentation

- CHANGELOG.md
- docs/backends/facebook_limited_login.rst
- docs/backends/index.rst
Add docs for Facebook Limited Login.
The new section looks like this:
> docs: add Facebook Limited Login backend

- docs/configuration/settings.rst
#238 Document lowercase email forcing
your code._
> Add documentation for forced lowercase emails

- docs/conf.py
- docs/images/logo.svg
- docs/index.rst
- docs/requirements.txt
This brings more modern look.
your code._
> feat: switch documentation to the furo theme

- docs/backends/cas.rst
- docs/backends/seznam.rst
- docs/intro.rst
> fix: various syntax fixes

- .readthedocs.yaml
> feat: fail rtd build on warning

- docs/pipeline.rst
- docs/strategies.rst
- docs/tests.rst
- docs/thanks.rst
> fix: corrected lists indentation

- docs/backends/apple.rst
- docs/pipeline.rst
> fix: correct ordered lists indent

- docs/backends/google.rst
Related ticket https://github.com/python-social-auth/social-core/pull/1015
> Google One Tap docs

- docs/backends/saml.rst
> docs(saml): describe lxml/xmlsec1 issues

- docs/configuration/django.rst
- docs/developer_intro.rst
- use current URLs syntax
- document namespaces behavior
- remove outdated backends
Fixes #273
Fixes #276
> fix(django): update Django documentation

- docs/installing.rst
> fix(install): update list of extras

- docs/backends/fedora.rst
This is related to https://github.com/python-social-auth/social-core/pull/1099
> Update the Fedora backend docs

- docs/backends/index.rst
- docs/backends/kick.rst
Add the required documentation for https://github.com/python-social-auth/social-core/issues/1096
> Add kick documentation

- docs/backends/google.rst
See https://github.com/python-social-auth/social-app-django/issues/275
> Document need for additional deps for Google One Tap
